Feature 3 expand view
Yi-Jacob/ajax-project pull request #8
Opened 2022-03-04 20:24 UTC by jacobyi11

https://user-images.githubusercontent.com/96788421/156836342-30d6ac2e-9708-4a6c-be17-6fff9156e27a.mov

https://user-images.githubusercontent.com/96788421/156836363-e796a8cd-ba63-4e50-8207-d36d3748df5c.mov

2022-03-04 20:27 UTC, codingcodymiller requested changes

2022-03-04 20:27 UTC, codingcodymiller commented on js/main.js
> +  }
Why is this function definition inside of another function definition? You should move this to the global scope

2022-03-04 20:27 UTC, codingcodymiller commented on js/main.js
> +  }
Why is this function definition inside of another function definition? You should move this to the global scope

2022-03-05 18:20 UTC, jacobyi11 commented
https://user-images.githubusercontent.com/96788421/156895422-e06d0a4f-dc5f-4c2f-b271-25fdf79b31cd.mov

2022-03-05 18:46 UTC, codingcodymiller approved these changes

2022-03-06 22:52 UTC, merged